site_name: iFluid Documentation
nav:
    - Home: index.md
    - Documentation of main classes:
        - iFluidCore: iFluidCore.md
        - iFluidSolver: iFluidSolver.md
        - iFluidTensor: iFluidTensor.md
    - Additional features:
        - Correlation functions: correlations.md
    - Examples:
        - Running an iFluid calculation: LLexample.md
        - Implementing a new model: model.md
        - Implementing a new algorithm: solver.md

theme: readthedocs